[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
swc = "0.263.26"
swc_common = "0.31.16"
swc_ecma_ast = "0.106.6"
swc_ecma_parser = "0.136.8"
swc_error_reporters = "0.15.18"
parking_lot = "0.12.1"
swc_ecma_lints = "0.84.14"
swc_ecma_transforms_base = "0.129.14"
swc_ecma_visit = "0.92.5"
